### ISSUE TITLE
help needed - can't see volumetric rendering (blurred image)

### ISSUE THREAD

**Issue by ShirKol** [uhhhci/immersive-ngp#11]
Hi,
 playing on GTX 1660ti , using fox demo, no DLLS, I am getting blurred image as follow:

![Screenshot 2023-01-14 011634](https://user-images.githubusercontent.com/17873014/212435961-dd3af8c2-d874-4e17-a5d9-780005d4f1dc.png)

why can't I see the fox?

**Comment by keli95566** [comment]
Hi there! Are you connected to steam VR and a VR headset? If so, you could use the VR controllers to navigate around the scene in order to change the viewing angle. Hope that this helps!

**Comment by ShirKol** [comment]
can it done manually before run ? by code or configuration? I am not succeeding to do so with the controllers.

**Comment by andybak** [comment]
> why can't I see the fox?

Are you sure that isn't the fox? You might be too close or looking at the wrong part of the scene.

**Comment by ShirKol** [comment]
found the fox ! :) thank you
