### ISSUE TITLE
cmake build error which is about "optix_ptx.h.rule"

### ISSUE THREAD

**Issue by mspark2023** [uhhhci/immersive-ngp#13]
Hi I built your code by your readme file guidance, but I always got this error.

![화면 캡처 2023-02-20 104337](https://user-images.githubusercontent.com/81412733/219990807-574d7482-eb4f-48cb-a769-06dd7e1bacf2.png)

My Environment:
windows 11
cuda 11.6
cmake 3.26
windows Developer Command Prompt
visual studio 2022 

After Run `cmake . -B build`, I got this. 
I add some print message. It looks no error when I build `CMakeList.txt` file

![화면 캡처 2023-02-20 103507](https://user-images.githubusercontent.com/81412733/219991256-a8720dc0-67e3-482d-b3e9-26ae7090687d.png)

Then I run `cmake --build build --config RelWithDebInfo -j`, I got some error about `optix_ptx.h.rule`.

AND I can build and run nvidia `instant-ngp` repo successfully in same environment. 

What did I miss? Could you give me some suggestions?

**Comment by keli95566** [comment]
Sorry that we might indeed missing the "cmake/bin2c_wrapper.cmake" file under "instant-ngp" folder. We added it back and hope that it fixs the build issue.
