### ISSUE TITLE
Does immersive-ngp support official integrated installation packages？

### ISSUE THREAD

**Issue by schauberger** [uhhhci/immersive-ngp#15]
Now that instant-ngp has official integrated installation packages, can immersive-ngp directly support it?
![Screenshot_20230503_031354_com android chrome](https://user-images.githubusercontent.com/129586229/235764320-521dc158-74cb-4f04-b39e-322afdca2d7b.png)

**Comment by TheTimmy** [comment]
Hey there,

we do not plan to provide an installation package for immersive-ngp in the near future. Currently, our implementation depends on the provided instant-ngp version to avoid conflicts when generating and loading NeRF scenes. However, you are welcome to submit a pull request to provide this feature.
