### ISSUE TITLE
No nvngx_dlss.dll

### ISSUE THREAD

**Issue by USTBVEO** [uhhhci/immersive-ngp#17]
In step 5, I want to copy ngp_shared.dll, ngp_shared.pdb and nvngx_dlss.dll and find that there is no such file "nvngx_dlss.dll" as in the instruction said. Is anyone faced with the same problem?

![1692001462051](https://github.com/uhhhci/immersive-ngp/assets/50726335/e35fdf3d-8c6f-4cbb-9d2a-893af081f12a)

**Comment by CarettaCaretta11** [comment]
Did you manage to fix it?

**Comment by USTBVEO** [comment]
no



发自我的iPhone


------------------ Original ------------------
From: Kamran ***@***.***&gt;
Date: Fri, Sep 22, 2023 2:57 PM
To: uhhhci/immersive-ngp ***@***.***&gt;
Cc: WEI YANG ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [uhhhci/immersive-ngp] No nvngx_dlss.dll (Issue #17)





 
Did you manage to fix it?

**Comment by TheTimmy** [comment]
Hey, this might happen depending on if your hardware supports DLSS. If you have an older hardware it will not have a "nvngx_dlss.dll". However, this should not be a problem as it will work regardless but just won't provide any DLSS support.
